apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-child-app-example
spec:
  destination:
    name: in-cluster
    namespace: argocd
    server: ''
  source:
    path: applicationset/parent
    repoURL: 'https://github.com/ankursaini2006/argocd-examples'
    targetRevision: example
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions: []
  info:
    - name: 'ParentAppSet:'
      value: 'https://github.com/ankursaini2006/argocd-examples'
