apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: parent-crossplane
spec:
  generators:
  - list:
      elements:
      - appname: ns1
        namespace: ns1
        cluster: in-cluster
      - appname: ns2
        namespace: ns2
        cluster: in-cluster
  - clusters: {}
  template:
    metadata:
      name: "{{appname}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/ankursaini2006/argocd-examples.git
        targetRevision: example
        path: "applicationset/child"
        kustomize:
          patches:
          - target:
              kind: ApplicationSet
              name: child-appset
            patch: |-
              - op: replace
                path: /metadata/name
                value: "child-appset-{{appname}}"
              - op: replace
                path: /spec/generators/0/list/elements/0/appName
                value: "child-app-{{appname}}"
              - op: replace
                path: /spec/template/spec/destination/name
                value: "{{cluster}}"
              - op: replace
                path: /spec/template/spec/destination/namespace
                value: "{{namespace}}"
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true