apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: parent-crossplane
spec:
  generators:
  - list:
      elements:
      - appName: app1
        namespace: ns-app1
        cluster: in-cluster
      - appName: app2
        namespace: ns-app2
        cluster: in-cluster
  - clusters: {}
  template:
    metadata:
      name: "parent-{{appName}}-crossplane"
    spec:
      project: default
      source:
        repoURL: https://github.com/ankursaini2006/argocd-examples.git
        targetRevision: example
        path: "applicationset/child"
        kustomize:
          namePrefix: "test"
          patches:
          - target:
              kind: ApplicationSet
              name: child-appset
            patch: |-
              - op: replace
                path: /metadata/name
                value: "child-appset-{{appName}}"
              - op: replace
                path: /spec/template/spec/destination/name
                value: "{{cluster}}"
              - op: replace
                path: /spec/template/spec/destination/namespace
                value: "{{namespace}}"
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true